# Generated by Django 4.1 on 2022-08-09 20:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GuildedUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('guilded_id', models.CharField(blank=True, max_length=200)),
                ('gumroad_license', models.CharField(blank=True, max_length=100)),
                ('is_banned', models.BooleanField(default=False)),
                ('ban_reason', models.CharField(blank=True, max_length=255)),
                ('banned_on', models.DateTimeField(blank=True)),
                ('verification_salt', models.CharField(blank=True, max_length=255)),
                ('verified', models.BooleanField(default=False, max_length=255)),
                ('invites_allowed', models.SmallIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('gumroad_id', models.CharField(max_length=200)),
                ('guilded_role_id', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gumroad.guildeduser')),
            ],
        ),
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gumroad.guildeduser')),
                ('to_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_user', to='gumroad.guildeduser')),
            ],
        ),
        migrations.AddField(
            model_name='guildeduser',
            name='subscription',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='gumroad.subscription'),
        ),
    ]
