# Generated by Django 4.1 on 2022-08-09 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gumroad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guildeduser',
            name='ban_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guildeduser',
            name='banned_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guildeduser',
            name='guilded_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guildeduser',
            name='gumroad_license',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guildeduser',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gumroad.subscription'),
        ),
        migrations.AlterField(
            model_name='guildeduser',
            name='verification_salt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='guildeduser',
            name='verified',
            field=models.BooleanField(default=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invites',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_user', to='gumroad.guildeduser'),
        ),
    ]
