# Generated by Django 4.1 on 2022-08-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gumroad', '0002_alter_guildeduser_ban_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildeduser',
            name='guilded_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
