# Generated by Django 4.1 on 2022-08-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gumroad', '0003_guildeduser_guilded_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='gumroad_permalink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='guilded_role_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='gumroad_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
