# Generated by Django 4.1 on 2022-08-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gumroad', '0004_subscription_gumroad_permalink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='invites_allowed',
            field=models.IntegerField(default=0),
        ),
    ]
