# Generated by Django 4.1 on 2022-08-11 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gumroad', '0005_subscription_invites_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guildeduser',
            name='verification_salt',
        ),
    ]
