# Generated by Django 4.1 on 2022-08-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gumroad', '0006_remove_guildeduser_verification_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='type',
            field=models.CharField(choices=[('Label', 'Label'), ('Application Setting', 'Application Setting'), ('Integration Id', 'Integration Id')], default='Label', max_length=100),
        ),
    ]
