# Generated by Django 4.1 on 2022-08-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gumroad', '0007_configuration_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.CharField(max_length=200)),
                ('debug', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('Network Error', 'Network Error'), ('Application Error', 'Application Error'), ('Misc', 'Misc')], default='Misc', max_length=100)),
            ],
        ),
    ]
