# Generated by Django 4.1 on 2022-08-12 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gumroad', '0008_integrationerror'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invites',
            new_name='Invite',
        ),
    ]
