# Generated by Django 4.1 on 2022-08-14 04:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gumroad', '0010_guildeduser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profanity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=200)),
                ('must_be_start_of_word', models.BooleanField(default=True)),
                ('how_to_handle', models.CharField(choices=[('Censor word', 'Censor word'), ('Delete message', 'Delete message'), ('Instant ban', 'Instant Ban'), ('Delete and mute user', 'Delete and mute user'), ('Leave and notify moderator', 'Leave and notify moderator')], default='Censor word', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='guildeduser',
            name='muted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
