# Generated by Django 4.1 on 2022-08-15 05:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gumroad', '0011_profanity_guildeduser_muted_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('run_function', models.CharField(choices=[('unmute', 'Unmute User'), ('pullTweets', 'Post New Tweets to Channel'), ('pullFromWeb', 'Pull data from website')], max_length=200)),
                ('function_parameters', models.TextField()),
                ('paused', models.BooleanField(default=False)),
                ('repeatsEvery', models.CharField(choices=[('Never', 'Never'), ('2', '2 Minutes'), ('10', '10 Minutes'), ('30', '30 Minutes'), ('60', '1 Hour'), ('240', '4 Hours'), ('720', '12 Hours'), ('1440', '24 Hours')], default='Never', max_length=100)),
                ('next_run', models.DateTimeField(auto_now_add=True)),
                ('job_data', models.BinaryField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='profanity',
            options={'verbose_name_plural': 'Profanities'},
        ),
    ]
