# Generated by Django 4.1 on 2022-08-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gumroad', '0012_scheduledjob_alter_profanity_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledjob',
            old_name='repeatsEvery',
            new_name='repeats_every',
        ),
    ]
