# Generated by Django 4.1 on 2022-08-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gumroad', '0013_rename_repeatsevery_scheduledjob_repeats_every'),
    ]

    operations = [
        migrations.AddField(
            model_name='profanity',
            name='word_to_swap',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profanity',
            name='how_to_handle',
            field=models.CharField(choices=[('Censor word', 'Censor word'), ('Delete message', 'Delete message'), ('Instant ban', 'Instant ban'), ('Swap word with another', 'Swap word with another'), ('Delete and mute user', 'Delete and mute user'), ('Leave and notify moderator', 'Leave and notify moderator')], default='Censor word', max_length=100),
        ),
    ]
