# Generated by Django 4.1 on 2022-08-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gumroad', '0014_profanity_word_to_swap_alter_profanity_how_to_handle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledjob',
            name='repeats_every',
        ),
        migrations.AlterField(
            model_name='configuration',
            name='type',
            field=models.CharField(choices=[('Application Setting', 'Application Setting'), ('Integration Id', 'Integration Id'), ('Command Label', 'Command Label'), ('Label', 'Label')], default='Label', max_length=100),
        ),
    ]
