# Generated by Django 4.1 on 2022-08-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gumroad', '0016_alter_scheduledjob_job_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildeduser',
            name='gumroad_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='integrationerror',
            name='type',
            field=models.CharField(choices=[('Network Error', 'Network Error'), ('Application Error', 'Application Error'), ('Bot Error', 'Bot Error'), ('Misc', 'Misc')], default='Misc', max_length=100),
        ),
        migrations.AlterField(
            model_name='profanity',
            name='how_to_handle',
            field=models.CharField(choices=[('Censor word', 'Censor word'), ('Delete message', 'Delete message'), ('Instant ban', 'Instant ban'), ('Swap word with another', 'Swap word with another'), ('Delete and mute user', 'Delete and mute user')], default='Censor word', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='job_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='run_function',
            field=models.CharField(choices=[('unmute', 'Unmute User'), ('tweetstream', 'Post New Tweets to Channel'), ('licensecheck', 'Check Gumroad Licenses')], max_length=200),
        ),
    ]
